export { default as Hamburger } from "./hamburger.svg";
export { default as BackIcon } from "./back-icon.svg";
export { default as NextArrow } from "./next-arrow.svg";
export { default as PrevArrow } from "./prev-arrow.svg";
export { default as UpArrow } from "./up-arrow.svg";
export { default as DownArrow } from "./down-arrow.svg";
export { default as Marker } from "./marker.svg";
export { default as markerUrl } from "./marker.svg?url";
export { default as EmptyHeart } from "./empty-heart.svg";
